In [21]:
import os
from pathlib import Path
from re import I
import pandas as pd

path=Path(r'D:\Kartik\IIITB\Study\Sem 3\PE\Kedro\kartik-eeg\data\02_intermediate\video_data\1_to_15\taskwise_vid_stamps')
df=pd.DataFrame(columns=['task','file','start','end'])
for file in os.listdir(path):
    if file.endswith('.csv'):
        df_file=pd.read_csv(path/file)
        df_file['participant']=str(int(file[:-4]))
        df=pd.concat([df,df_file],ignore_index=True, sort=True)
        # print(len(df_file), len(df))
save_path=Path(r'D:\Kartik\IIITB\Study\Sem 3\PE\Kedro\kartik-eeg\data\02_intermediate\video_data\1_to_15')
df=df.reindex(columns=['participant','task','file','start','end'])
df.to_csv(save_path/"trainingVidStamps.csv", index=False)
df

    participant task  file  start    end
0             1    1  1.py  04-09  04:25
1             1    1  1.py  04:34  05:08
2             1    1  1.py  05:12  05:25
3             1    1  1.py  05:41  06:33
4             1    1  2.py  07:14  07:16
..          ...  ...   ...    ...    ...
228          14    2   2.c  35:03  35:53
229          14    2  3.py  36:23  36:28
230          14    2  3.py  38:28  38:58
231          14    2  3.py  39:38  40:18
232          14    2  3.py  40:28  40:48

[233 rows x 5 columns]